### PR TITLE
Sidebar navigation

### PR DESCRIPTION
**Pull request by rukawa444**
This PR added a sidebar navigation css animation.

sidebar

### CODE REVIEW

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-4)

**Comment by rukawa444** [comment]
> Go go go 😄

Thanks!!

**Comment by rukawa444** [comment]
I can't seem to figure out what was wrong with the prettier...

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-4)

**Comment by jkettmann** [comment]
Nice 👍

**Comment by jkettmann** [comment]
Let me know in Discord if you struggle with resolving the merge conflict

**Pull request closed without merging**
